language: python
python:
  - "3.5"
  - "3.6"


# Hack to fix broken boto package on travis
before_install:
  - export BOTO_CONFIG=/dev/null

install:
  travis_wait pip install -r requirements

script:
  cd tests; python -m pytest
